POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/registration
Content-Type: application/json

{
  "username": "admin",
  "password": "1"
}

####

POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/authentication
Content-Type: application/json

{
  "username": "admin",
  "password": "1"
}

###

POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6ImRhbmlsIiwiaWF0IjoxNzM3MDc3MTM3LCJpc3MiOiJ5ZXN0YWkiLCJleHAiOjE3MzcwODA3Mzd9.jUOGLnNn7-EMXMKvd3kI7mHCVylWEBCFGZRi--o6AeU

{
  "address": "Санкт-Петербург, Кронверский проспект",
  "type": "STOCK",
  "name": "ITMO University"
}

###

POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/cargo-requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6ImRhbmlsIiwiaWF0IjoxNzM3MDYwNTY4LCJpc3MiOiJ5ZXN0YWkiLCJleHAiOjE3MzcwNjQxNjh9._sfkvC-iDxGvi6hTVMcddvJBaGF4LiGlL1YBNBQZa7Y

{
  "name": "danil",
  "cargoType": "FRIDGE",
  "receptionCenter": 3,
  "destinationCenter": 3
}

###

GET http://localhost:9090/insys-1-1.0-SNAPSHOT/api/cargo-requests/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6IjIiLCJpYXQiOjE3MzY3OTA1NjcsImlzcyI6Inllc3RhaSIsImV4cCI6MTczNjc5NDE2N30.5Jo-DlJIeVHmBVJKmV1qV3S_xsrV5nQBo_fJBADLi9g

###

###

POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/orders/danil
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6ImRhbmlsIiwiaWF0IjoxNzM3MDcyMzMyLCJpc3MiOiJ5ZXN0YWkiLCJleHAiOjE3MzcwNzU5MzJ9.Z9xDsSaa6aMkYg3sXAOPybhmLOMCRnq2rCWMUF9ozt0
###

POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/labels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6ImRhbmlsIiwiaWF0IjoxNzM3MDcyMzMyLCJpc3MiOiJ5ZXN0YWkiLCJleHAiOjE3MzcwNzU5MzJ9.Z9xDsSaa6aMkYg3sXAOPybhmLOMCRnq2rCWMUF9ozt0
###

POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/cargoes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6ImRhbmlsIiwiaWF0IjoxNzM3MDcyMzMyLCJpc3MiOiJ5ZXN0YWkiLCJleHAiOjE3MzcwNzU5MzJ9.Z9xDsSaa6aMkYg3sXAOPybhmLOMCRnq2rCWMUF9ozt0

{
  "cargoRequestId": "1",
  "weight": "25",
  "orderId": 5,
  "labelId": 10
}

###

GET http://localhost:9090/insys-1-1.0-SNAPSHOT/api/cargoes/012345673145517462
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6IjEiLCJpYXQiOjE3MzY3OTE4MzEsImlzcyI6Inllc3RhaSIsImV4cCI6MTczNjc5NTQzMX0.Ef5k2JiaCPhXzoarjySkmwGJMrLJrEPFU2UtjBnfF0E

###

POST http://localhost:9090/insys-1-1.0-SNAPSHOT/api/incidents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6IjIiLCJpYXQiOjE3MzY4NDU4MjgsImlzcyI6Inllc3RhaSIsImV4cCI6MTczNjg0OTQyOH0.fHCWvFg5tcuaazBcCEw3lDPPtLtVxxoqMze4dungHv0

{
  "ssccCode": "012345673145517462",
  "description": "Треснул корпус у груза",
  "type": "BROKEN"
}

###

PATCH http://localhost:9090/insys-1-1.0-SNAPSHOT/api/cargo-status/012345673145517462
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6IjIiLCJpYXQiOjE3MzY4NDU4MjgsImlzcyI6Inllc3RhaSIsImV4cCI6MTczNjg0OTQyOH0.fHCWvFg5tcuaazBcCEw3lDPPtLtVxxoqMze4dungHv0

{
  "locationId": "1",
  "cargoStatusDelivery": "IN_PROGRESS"
}